"""create issues and issue_attachments tables

Revision ID: 1f791d55089e
Revises: b1756873e852
Create Date: 2026-08-11 20:46:49.376030

Standard tenant-table RLS policy on both tables (see b2404d3544c5's module
docstring for the template).
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1f791d55089e'
down_revision: str | Sequence[str] | None = 'b1756873e852'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLES = ("issues", "issue_attachments")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sa.Enum('minor', 'major', 'critical', 'blocker', name='issueseverity'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='issuepriority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', 'wont_fix', name='issuestatus'), nullable=False),
    sa.Column('assignee_user_id', sa.Uuid(), nullable=True),
    sa.Column('source_test_case_id', sa.Uuid(), nullable=True),
    sa.Column('source_test_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_test_case_id'], ['test_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_test_run_id'], ['test_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_organization_id'), 'issues', ['organization_id'], unique=False)
    op.create_index('ix_issues_organization_id_severity', 'issues', ['organization_id', 'severity'], unique=False)
    op.create_index(op.f('ix_issues_project_id'), 'issues', ['project_id'], unique=False)
    op.create_index('ix_issues_project_id_status', 'issues', ['project_id', 'status'], unique=False)
    op.create_table('issue_attachments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('screenshot', 'log', name='issueattachmenttype'), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issue_attachments_issue_id', 'issue_attachments', ['issue_id'], unique=False)
    op.create_index(op.f('ix_issue_attachments_organization_id'), 'issue_attachments', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    for table in _TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_attachments_organization_id'), table_name='issue_attachments')
    op.drop_index('ix_issue_attachments_issue_id', table_name='issue_attachments')
    op.drop_table('issue_attachments')
    op.drop_index('ix_issues_project_id_status', table_name='issues')
    op.drop_index(op.f('ix_issues_project_id'), table_name='issues')
    op.drop_index('ix_issues_organization_id_severity', table_name='issues')
    op.drop_index(op.f('ix_issues_organization_id'), table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
