"""create test_runs test_run_cases test_results tables

Revision ID: 29caac081114
Revises: 57870bd3c84c
Create Date: 2026-08-11 15:21:20.826049

Standard tenant-table RLS policy on all three tables (see b2404d3544c5's
module docstring for the template).
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29caac081114'
down_revision: str | Sequence[str] | None = '57870bd3c84c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLES = ("test_runs", "test_results", "test_run_cases")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('initiated_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'error', name='testrunstatus'), nullable=False),
    sa.Column('summary_total', sa.Integer(), nullable=False),
    sa.Column('summary_passed', sa.Integer(), nullable=False),
    sa.Column('summary_failed', sa.Integer(), nullable=False),
    sa.Column('summary_skipped', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_organization_id'), 'test_runs', ['organization_id'], unique=False)
    op.create_index('ix_test_runs_organization_id_status', 'test_runs', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_test_runs_project_id'), 'test_runs', ['project_id'], unique=False)
    op.create_index('ix_test_runs_project_id_created_at', 'test_runs', ['project_id', 'created_at'], unique=False)
    op.create_table('test_results',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_run_id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('passed', 'failed', 'skipped', 'error', name='testresultstatus'), nullable=False),
    sa.Column('execution_log', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('failure_step_index', sa.Integer(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_organization_id'), 'test_results', ['organization_id'], unique=False)
    op.create_index('ix_test_results_organization_id_status', 'test_results', ['organization_id', 'status'], unique=False)
    op.create_index('ix_test_results_test_case_id_created', 'test_results', ['test_case_id', 'started_at'], unique=False)
    op.create_index('ix_test_results_test_run_id', 'test_results', ['test_run_id'], unique=False)
    op.create_table('test_run_cases',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_run_id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_run_id', 'test_case_id', name='uq_test_run_cases_run_case')
    )
    op.create_index(op.f('ix_test_run_cases_organization_id'), 'test_run_cases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_test_run_cases_test_run_id'), 'test_run_cases', ['test_run_id'], unique=False)
    # ### end Alembic commands ###

    for table in _TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in reversed(_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_run_cases_test_run_id'), table_name='test_run_cases')
    op.drop_index(op.f('ix_test_run_cases_organization_id'), table_name='test_run_cases')
    op.drop_table('test_run_cases')
    op.drop_index('ix_test_results_test_run_id', table_name='test_results')
    op.drop_index('ix_test_results_test_case_id_created', table_name='test_results')
    op.drop_index('ix_test_results_organization_id_status', table_name='test_results')
    op.drop_index(op.f('ix_test_results_organization_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index('ix_test_runs_project_id_created_at', table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_project_id'), table_name='test_runs')
    op.drop_index('ix_test_runs_organization_id_status', table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_organization_id'), table_name='test_runs')
    op.drop_table('test_runs')
    # ### end Alembic commands ###
