"""add created_test_case_ids to generation_runs

Revision ID: 3f14c9719735
Revises: 163f553ef31a
Create Date: 2026-08-11 12:14:52.403482

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f14c9719735'
down_revision: str | Sequence[str] | None = '163f553ef31a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_runs', sa.Column('created_test_case_ids', postgresql.ARRAY(sa.Uuid()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_runs', 'created_test_case_ids')
    # ### end Alembic commands ###
