"""add capture_screenshot to test_steps

Revision ID: 57870bd3c84c
Revises: 3f14c9719735
Create Date: 2026-08-11 13:06:28.118775

server_default='false' added manually (not autogenerated): existing
test_steps rows from Phases 8-9 need a value for this new NOT NULL column.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '57870bd3c84c'
down_revision: str | Sequence[str] | None = '3f14c9719735'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'test_steps', sa.Column('capture_screenshot', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_steps', 'capture_screenshot')
    # ### end Alembic commands ###
