"""index audit: add refresh_tokens and usage_records composite indexes

Revision ID: 779d90e569e8
Revises: 5d0f54677696
Create Date: 2026-08-12 09:57:38.757325

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '779d90e569e8'
down_revision: str | Sequence[str] | None = '5d0f54677696'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_refresh_tokens_user_id_revoked_at', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_index('ix_usage_records_organization_id_metric', 'usage_records', ['organization_id', 'metric'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_records_organization_id_metric', table_name='usage_records')
    op.drop_index('ix_refresh_tokens_user_id_revoked_at', table_name='refresh_tokens')
    # ### end Alembic commands ###
