"""create ai_analyses table

Revision ID: b1756873e852
Revises: 8cddc9c38efd
Create Date: 2026-08-11 17:12:32.218806

Standard tenant-table RLS policy (see b2404d3544c5's module docstring for
the template).
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b1756873e852'
down_revision: str | Sequence[str] | None = '8cddc9c38efd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLE = "ai_analyses"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_result_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('completed', 'failed', name='aianalysisstatus'), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('root_cause', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sa.Enum('minor', 'major', 'critical', 'blocker', name='analysisseverity'), nullable=True),
    sa.Column('suggested_fix', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_organization_id'), 'ai_analyses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_test_result_id'), 'ai_analyses', ['test_result_id'], unique=False)
    op.create_index('ix_ai_analyses_test_result_id_created_at', 'ai_analyses', ['test_result_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    op.execute(f"ALTER TABLE {_TABLE} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {_TABLE} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON {_TABLE}
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {_TABLE}")
    op.execute(f"ALTER TABLE {_TABLE} NO FORCE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {_TABLE} DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_analyses_test_result_id_created_at', table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_test_result_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_organization_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
