"""create usage_records with standard RLS policy

Revision ID: b2404d3544c5
Revises: f3b10cfbb684
Create Date: 2026-08-10 14:39:07.451160

This is the first table to use the **standard** (single-condition) RLS
policy template established by the rls_role_and_policies migration
(0e1c705a31ba) for `memberships`'s special OR-clause case — plain tenant
tables only need the one condition below. Every future migration that adds
an Organization-scoped table MUST apply this same three-statement pattern
(ENABLE, FORCE, CREATE POLICY ... USING (organization_id = ...)) — this is
the "document the pattern new tables must follow" T073 requires, made
concrete by example rather than only in prose.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b2404d3544c5'
down_revision: str | Sequence[str] | None = 'f3b10cfbb684'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLE = "usage_records"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_records',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('metric', sa.Enum('projects', 'test_executions', 'ai_operations', 'members', name='usagemetric'), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'period_start', 'metric', name='uq_usage_org_period_metric')
    )
    op.create_index(op.f('ix_usage_records_organization_id'), 'usage_records', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    # --- Standard tenant-table RLS policy (see module docstring) ---
    op.execute(f"ALTER TABLE {_TABLE} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {_TABLE} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON {_TABLE}
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )


def downgrade() -> None:
    op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {_TABLE}")
    op.execute(f"ALTER TABLE {_TABLE} NO FORCE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {_TABLE} DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_organization_id'), table_name='usage_records')
    op.drop_table('usage_records')
    # ### end Alembic commands ###
