"""create test_cases and test_steps tables with RLS

Revision ID: e1cdd38d5e65
Revises: 7e926ab0192b
Create Date: 2026-08-11 11:08:50.983174

Standard tenant-table RLS policy (see b2404d3544c5's module docstring for
the template) on both tables — not something autogenerate can detect,
since alembic's schema comparison has no concept of RLS POLICY objects.
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1cdd38d5e65'
down_revision: str | Sequence[str] | None = '7e926ab0192b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='testcasepriority'), nullable=False),
    sa.Column('severity', sa.Enum('minor', 'major', 'critical', 'blocker', name='testcaseseverity'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'rejected', name='testcasestatus'), nullable=False),
    sa.Column('source', sa.Enum('ai_generated', 'manual', name='testcasesource'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_result', sa.Enum('passed', 'failed', 'skipped', 'not_run', name='testcaseresult'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', title || ' ' || description)", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_organization_id'), 'test_cases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_test_cases_project_id'), 'test_cases', ['project_id'], unique=False)
    op.create_index('ix_test_cases_project_id_status', 'test_cases', ['project_id', 'status'], unique=False)
    op.create_index('ix_test_cases_search_vector', 'test_cases', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_test_cases_tags', 'test_cases', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('test_steps',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('navigate', 'click', 'type', 'submit', 'assert_url', 'assert_content', 'assert_element', name='teststepactiontype'), nullable=False),
    sa.Column('target_descriptor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expected_assertion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_id', 'order_index', name='uq_test_steps_case_order')
    )
    op.create_index(op.f('ix_test_steps_organization_id'), 'test_steps', ['organization_id'], unique=False)
    op.create_index(op.f('ix_test_steps_test_case_id'), 'test_steps', ['test_case_id'], unique=False)
    # ### end Alembic commands ###

    for _table in ("test_cases", "test_steps"):
        op.execute(f"ALTER TABLE {_table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {_table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {_table}
            USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    for _table in ("test_cases", "test_steps"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {_table}")
        op.execute(f"ALTER TABLE {_table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {_table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_steps_test_case_id'), table_name='test_steps')
    op.drop_index(op.f('ix_test_steps_organization_id'), table_name='test_steps')
    op.drop_table('test_steps')
    op.drop_index('ix_test_cases_tags', table_name='test_cases', postgresql_using='gin')
    op.drop_index('ix_test_cases_search_vector', table_name='test_cases', postgresql_using='gin')
    op.drop_index('ix_test_cases_project_id_status', table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_project_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_organization_id'), table_name='test_cases')
    op.drop_table('test_cases')
    # ### end Alembic commands ###
